### ISSUE TITLE
Add A Light Control Bar

### ISSUE THREAD

**Issue by BHM-Bob** [Jax-Core/MIUI-Shade#5]
I appreciate your work, and I think it will be better to add a screen brightness adjustment bar as you did for volume.
Anyway, thank you for your great works!

**Comment by EnhancedJax** [comment]
Glad you liked it! Unfortunately, MIUI-Shade is discontinued. You can try out [ValliStart](https://github.com/Jax-Core/ValliStart) instead, though that still doesn't have the light controls *yet*.
