### ISSUE TITLE
Multi screen incompatibility 

### ISSUE THREAD

**Issue by Annoying-Gasta** [Jax-Core/MIUI-Shade#6]
While having multiple screens of different aspect ratios, the skin will place itself in the middle no matter what
![Screenshot (4)](https://user-images.githubusercontent.com/109389067/179307200-f6866cf6-0be0-4d39-a366-a4c7be69633e.png)

**Comment by EnhancedJax** [comment]
Try changing `JaxCore -> MIUI-Shade -> General -> Setting: Index of screen to display on`, if this doesn't fix the problem, I am afraid you'll have to try to fix it yourself. Unfortunately I have ended support for this module.
